# Generated by Django 4.1.1 on 2022-09-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Популярный город',
                'verbose_name_plural': 'Популярные города',
                'db_table': 'popular_city',
            },
        ),
    ]
