# Generated by Django 4.1.1 on 2022-09-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_name_popularcity_city_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="popularcity",
            name="city_name",
            field=models.CharField(max_length=255),
        ),
    ]
